spring:
  application:
    name: appetizer-service
  cloud:
    client:
      hostname: localhost

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

wfd:
  appetizer:
    order: 1
    type: appetizer
    menu:
      - Hummus
      - Crab Cakes
      - Mozzerella Sticks
