apiVersion: v1
kind: Service
metadata:
  name: "wfddessert-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 9080
  - name: https
    port: 9443

  selector:
    app: "wfdappetizer-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "wfdappetizer-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "wfdappetizer-selector"
    spec:
      containers:
      - name: wfdappetizer
        image: wfdappetizer:v1.0.0
        readinessProbe:
          httpGet:
            path: /WfdAppetizer/rest/appetizer
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /WfdAppetizer/rest/appetizer
            port: 9080
          initialDelaySeconds: 1500
          timeoutSeconds: 500
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
