apiVersion: v1
description: A Helm chart for the Spring Cloud version of the appetizer microservice of the What's For Dinner application
name: wfd-appetizer
version: latest
appVersion: Spring-Cloud-v1
